server:
  port: 8080
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful
spring:
  application:
    name: gateway-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      default-uri: host.docker.internal
      default-path: /api/v1
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      routes:
        - id: user-service
          uri: ${spring.cloud.gateway.default-uri}:9001
          predicates:
            - Path=${spring.cloud.gateway.default-path}/user/**
          filters:
            - SetRequestHeader=X-User-Id,
            - SetRequestHeader=X-User-Key,
        - id: pet-service
          uri: ${spring.cloud.gateway.default-uri}:9002
          predicates:
            - Path=${spring.cloud.gateway.default-path}/pet/**
          filters:
            - SetRequestHeader=X-User-Id,
            - SetRequestHeader=X-User-Key,
        - id: account-service
          uri: ${spring.cloud.gateway.default-uri}:9003
          predicates:
            - Path=${spring.cloud.gateway.default-path}/account/**
          filters:
            - SetRequestHeader=X-User-Id,
            - SetRequestHeader=X-User-Key,
        - id: picture-service
          uri: ${spring.cloud.gateway.default-uri}:9004
          predicates:
            - Path=${spring.cloud.gateway.default-path}/picture/**
          filters:
            - SetRequestHeader=X-User-Id,
            - SetRequestHeader=X-User-Key,
        - id: expense-service
          uri: ${spring.cloud.gateway.default-uri}:9005
          predicates:
            - Path=${spring.cloud.gateway.default-path}/expense/**
          filters:
            - SetRequestHeader=X-User-Id,
            - SetRequestHeader=X-User-Key,
        - id: schedule-service
          uri: ${spring.cloud.gateway.default-uri}:9006
          predicates:
            - Path=${spring.cloud.gateway.default-path}/schedule/**
          filters:
            - SetRequestHeader=X-User-Id,
            - SetRequestHeader=X-User-Key,
        - id: notification-service
          uri: ${spring.cloud.gateway.default-uri}:9007
          predicates:
            - Path=${spring.cloud.gateway.default-path}/notification/**
          filters:
            - SetRequestHeader=X-User-Id,
            - SetRequestHeader=X-User-Key,
        - id: frontend-s3
          uri: http://petsi-frontend-bucket.s3-website.ap-northeast-2.amazonaws.com/
          predicates:
            - Path=/, /*, /assets/**, /fonts/**, /images/**, index.html, /*.css, /*.js, /*.ts, /*.tsx, /Symbol.ico
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/petsi
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG