server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: gateway-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    gateway:
      x-forwarded:
        enabled: true
        for-enabled: true
        host-enabled: true
        port-enabled: true
        proto-enabled: true
      default-path: /api/v1
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      routes:
        - id: user-service
          uri: http://user-service:9001
          predicates:
            - Path=${spring.cloud.gateway.default-path}/user/**
          filters:
            - RemoveRequestHeader=X-Forwarded-Proto
            - AddRequestHeader=X-Forwarded-Proto, https
        - id: pet-service
          uri: http://pet-service:9002
          predicates:
            - Path=${spring.cloud.gateway.default-path}/pet/**
          filters:
            - RemoveRequestHeader=X-Forwarded-Proto
            - AddRequestHeader=X-Forwarded-Proto, https
        - id: account-service
          uri: http://account-service:9003
          predicates:
            - Path=${spring.cloud.gateway.default-path}/account/**
          filters:
            - RemoveRequestHeader=X-Forwarded-Proto
            - AddRequestHeader=X-Forwarded-Proto, https
        - id: picture-service
          uri: http://picture-service:9004
          predicates:
            - Path=${spring.cloud.gateway.default-path}/picture/**
          filters:
            - RemoveRequestHeader=X-Forwarded-Proto
            - AddRequestHeader=X-Forwarded-Proto, https
        - id: expense-service
          uri: http://expense-service:9005
          predicates:
            - Path=${spring.cloud.gateway.default-path}/expense/**
          filters:
            - RemoveRequestHeader=X-Forwarded-Proto
            - AddRequestHeader=X-Forwarded-Proto, https
        - id: schedule-service
          uri: http://schedule-service:9006
          predicates:
            - Path=${spring.cloud.gateway.default-path}/schedule/**
          filters:
            - RemoveRequestHeader=X-Forwarded-Proto
            - AddRequestHeader=X-Forwarded-Proto, https
        - id: notification-service
          uri: http://notification-service:9007
          predicates:
            - Path=${spring.cloud.gateway.default-path}/notification/**
          filters:
            - RemoveRequestHeader=X-Forwarded-Proto
            - AddRequestHeader=X-Forwarded-Proto, https
        - id: frontend-s3
          uri: http://petsi-frontend-bucket.s3-website.ap-northeast-2.amazonaws.com/
          predicates:
            - Path=/**
          filters:
            - RemoveRequestHeader=X-Forwarded-Proto
            - AddRequestHeader=X-Forwarded-Proto, https
            - RewritePath=(?<path>.*), $\{path}
  redis:
    host: redis-gateway-service
    port: 6379
    password: ${DB_PASSWORD}
    timeout: 5000