server:
  port: 80
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: gateway-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      routes:
        - id: user-service
          uri: http://petsi/user-service:9001
          predicates:
            - Path=/user/**
        - id: pet-service
          uri: http://petsi/pet-service:9002
          predicates:
            - Path=/pet/**
        - id: account-service
          uri: http://petsi/account-service:9003
          predicates:
            - Path=/account/**
        - id: picture-service
          uri: http://petsi/picture-service:9004
          predicates:
            - Path=/account/**
        - id: expense-service
          uri: http://petsi/expense-service:9005
          predicates:
            - Path=/account/**
        - id: schedule-service
          uri: http://petsi/schedule-service:9006
          predicates:
            - Path=/account/**
        - id: notification-service
          uri: http://petsi/notification-service:9007
          predicates:
            - Path=/account/**
        - id: frontend-s3
          uri: http://petsi-frontend-bucket.s3-website.ap-northeast-2.amazonaws.com/
          predicates:
            - Path=/,/assets/**, /fonts/**, index.html, /*.css,/*.js, /Symbol.ico