spring:
  application:
    name: pet-service
  datasource:
    url: jdbc:mysql://mysql_pet_service:3306/petsi_account?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: petsi
    password: petsi0909!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true

cloud:
  aws:
    s3:
      bucket: petsi-images-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAZ3MGNG6NT7HPQKVS
      secretKey: 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