spring:
  application:
    name: schedule-service
  config:
    import: optional:file:.env[.properties]
  server:
    port: 8080
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: false
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      format_sql: true
  output:
    ansi:
      enabled: always
springdoc:
  swagger-ui:
    path: /petsi/swagger-ui.html
