spring:
  application:
    name: picture-service
  profiles:
    include: aws
  datasource:
    url: jdbc:mysql://mysql_picture_service:3306/petsi_picture?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: petsi
    password: petsi0909!
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    enabled: false