spring:
  application:
    name: picture-service
  datasource:
    url: jdbc:mysql://mysql_picture_service:3306/petsi_picture?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: petsi
    password: petsi0909!
  flyway:
    enabled: false
  jpa:
      database: mysql
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
      show-sql: false
      hibernate:
        ddl-auto: none
        format_sql: true
#  data:
#    redis:
#      host: localhost
#      port: 6379

cloud:
  aws:
    s3:
      bucket: petsi-images-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAZ3MGNG6NT7HPQKVS
      secretKey: 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