export enum AppPaths {
    HOME = "/",
    LOGIN = "/login",
    SIGNUP = "/signup",
    FIND_PASSWORD = "/find-password",
    EXPENSE = "/expense",
    EXPENSE_DETAIL = "/expense-detail",
    EXPENSE_ADD = "/expense/add",
    EXPENSE_SUPPLIES = "/expense/add-supplies",
    EXPENSE_ITEM = "/expense-item",
    EXPENSE_MEDICAL = "/expense/add-medical",
    EXPENSE_FILTER = "/expense-filter",
    PETFRIENDS_LOGIN = "/petfriends-login",
    KAKAO_LOGIN = "/kakao-login",
    KAKAO_LOGIN_2FA = "/kakao-login-2fa",
    ACCOUNT = "/account",
    PRODUCT = "/account/product",
    PICTURE = "/picture",
    PICTURE_CREATE = "/picture/create",
    PICTURE_ALBUM = "/picture/album",
    MYPAGE = "/mypage",
    CHANGE_PASSWORD = "/change-password",
    ALERT_SETTINGS = "/alert-settings",
    ADD_PET = "/add-pet",
    SCHEDULE = "/schedule",
    NOTICE = "/notice",
}
