spring:
  application:
    name: account-service
  config:
    import: optional:file:.env[.properties]
  server:
    port: 8080
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: false
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      format_sql: true
  data:
    redis:
      host: j11a403.p.ssafy.io
      port: 6380
      password: ${DB_PASSWORD}
      timeout: 5000
  output:
    ansi:
      enabled: always
  fin:
    api_key: ${FIN_API_KEY}
    manager-account: ${MANAGER_ACCOUNT_NO}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
springdoc:
  swagger-ui:
    path: /petsi/swagger-ui.html

# Eureka 서버 주소
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

