spring:
  application:
    name: account-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: always
  fin:
    api_key: 2443ab151bab467083ba59ec8b9f6ef5
springdoc:
  swagger-ui:
    path: /api/v1/account/swagger-ui.html

logging:
  level:
    org.hibernate: DEBUG
    org.springframework: DEBUG
