spring:
  application:
    name: account-service
  server:
    port: 8080
    servlet:
      context-path: /petsi
  datasource:
    url: jdbc:mysql://localhost:3306/petsi_account?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: petsi
    password: petsi0909!
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      format_sql: true
  output:
    ansi:
      enabled: always
springdoc:
  swagger-ui:
    path: /petsi/swagger-ui.html
