spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://mysql_account_service:3306/petsi_account?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: false
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
      format_sql: true
  output:
    ansi:
      enabled: always
  fin:
    api-key: ${FIN_API_KEY}
springdoc:
  swagger-ui:
    path: /api/v1/account/swagger-ui.html

logging:
  level:
    org.hibernate: DEBUG
    org.springframework: DEBUG
